const bcrypt = require('bcryptjs');
const db = require('../config/database');
const authSessionService = require('../services/authSessionService');
const { get, all, run } = db.promises;
function normalizarEmail(v){return String(v||'').trim().toLowerCase();}
function publico(u){return{id:u.id,nome:u.nome,email:u.email,masp:u.masp,unidade:u.unidade,unidade_id:u.unidade_id||null,role:u.role||'usuario',ativo:Boolean(u.ativo)};}
async function resolverUnidade(body={},exigirAtiva=true){const id=Number(body.unidadeId||body.unidade_id||0);let unidade=null;if(id)unidade=await get('SELECT id,nome,ativo FROM unidades WHERE id=?',[id]);if(!unidade&&body.unidade)unidade=await get('SELECT id,nome,ativo FROM unidades WHERE lower(nome)=lower(?)',[String(body.unidade).trim()]);if(!unidade)return null;if(exigirAtiva&&!unidade.ativo)return null;return unidade;}
async function listarUnidadesPublicas(_req,res){try{await db.ready;const rows=await all('SELECT id,codigo_externo,nome FROM unidades WHERE ativo=1 ORDER BY ordem,nome COLLATE NOCASE');return res.json(rows);}catch(err){console.error(err);return res.status(500).json({erro:'Erro ao carregar unidades.'});}}
async function bootstrapStatus(_req,res){try{await db.ready;const r=await get('SELECT COUNT(*) AS n FROM usuarios');return res.json({precisaConfigurarAdministrador:!r?.n});}catch(err){console.error(err);return res.status(500).json({erro:'Erro ao verificar configuração inicial.'});}}
async function registrar(req,res){const{nome,email,senha,masp}=req.body||{};if(!nome||!email||!senha||!masp)return res.status(400).json({erro:'Preencha todos os campos obrigatórios.'});if(String(senha).length<8)return res.status(400).json({erro:'A senha deve possuir pelo menos 8 caracteres.'});try{await db.ready;const count=await get('SELECT COUNT(*) AS n FROM usuarios');if(count?.n)return res.status(403).json({erro:'O administrador inicial já foi configurado. Novos usuários devem ser criados no painel administrativo.'});const unidade=await resolverUnidade(req.body,true);if(!unidade)return res.status(400).json({erro:'Selecione uma unidade ativa cadastrada no Nexus.'});const hash=await bcrypt.hash(String(senha),10);const r=await run(`INSERT INTO usuarios (nome,email,senha,masp,unidade,unidade_id,role,ativo,criado_em,atualizado_em) VALUES (?,?,?,?,?,?,'admin',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`,[String(nome).trim(),normalizarEmail(email),hash,String(masp).trim(),unidade.nome,unidade.id]);return res.status(201).json({mensagem:'Administrador inicial cadastrado com sucesso.',usuarioId:r.lastID});}catch(err){if(String(err.message).includes('UNIQUE'))return res.status(409).json({erro:'Já existe uma conta com este e-mail.'});console.error(err);return res.status(500).json({erro:'Erro interno no servidor.'});}}
async function login(req,res){const email=normalizarEmail(req.body?.email),senha=String(req.body?.senha||'');if(!email||!senha)return res.status(400).json({erro:'Informe e-mail e senha.'});try{await db.ready;const u=await get('SELECT * FROM usuarios WHERE lower(email)=?',[email]);if(!u||!(await bcrypt.compare(senha,u.senha)))return res.status(401).json({erro:'E-mail ou senha incorretos.'});if(!u.ativo)return res.status(403).json({erro:'Este usuário está desativado. Procure um administrador.'});const{token,expiresAt}=await authSessionService.createSession(u.id);res.cookie(authSessionService.COOKIE_NAME,token,authSessionService.cookieOptions());return res.json({sucesso:true,expiresAt,usuario:publico(u)});}catch(err){console.error(err);return res.status(500).json({erro:'Erro interno no servidor.'});}}
async function sessaoAtual(req,res){try{await db.ready;const token=authSessionService.getTokenFromRequest(req);const u=await authSessionService.getAuthenticatedUser(token);if(!u){if(token)await authSessionService.deleteSession(token).catch(()=>{});res.clearCookie(authSessionService.COOKIE_NAME,authSessionService.clearCookieOptions());return res.status(401).json({autenticado:false});}return res.json({autenticado:true,usuario:publico(u),expiresAt:u.expiresAt});}catch(err){console.error(err);return res.status(500).json({erro:'Erro ao validar sessão.'});}}
async function logout(req,res){try{await authSessionService.deleteSession(authSessionService.getTokenFromRequest(req));}catch(err){console.error(err);}finally{res.clearCookie(authSessionService.COOKIE_NAME,authSessionService.clearCookieOptions());}return res.status(204).end();}
async function listarUsuarios(_req,res){try{await db.ready;const rows=await all(`SELECT id,nome,email,masp,unidade,unidade_id,role,ativo,criado_em,atualizado_em FROM usuarios ORDER BY CASE role WHEN 'admin' THEN 0 ELSE 1 END,nome COLLATE NOCASE`);return res.json(rows.map(u=>({...u,ativo:Boolean(u.ativo)})));}catch(err){console.error(err);return res.status(500).json({erro:'Erro ao buscar usuários.'});}}
async function criarUsuario(req,res){const{nome,email,masp,senha,role='usuario'}=req.body||{};if(!nome||!email||!masp||!senha)return res.status(400).json({erro:'Preencha todos os campos obrigatórios.'});if(!['admin','usuario'].includes(role))return res.status(400).json({erro:'Perfil de usuário inválido.'});if(String(senha).length<8)return res.status(400).json({erro:'A senha deve possuir pelo menos 8 caracteres.'});try{const unidade=await resolverUnidade(req.body,true);if(!unidade)return res.status(400).json({erro:'Selecione uma unidade ativa cadastrada no Nexus.'});const hash=await bcrypt.hash(String(senha),10);const r=await run(`INSERT INTO usuarios (nome,email,senha,masp,unidade,unidade_id,role,ativo,criado_em,atualizado_em) VALUES (?,?,?,?,?,?,?,1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`,[String(nome).trim(),normalizarEmail(email),hash,String(masp).trim(),unidade.nome,unidade.id,role]);return res.status(201).json({mensagem:'Usuário criado com sucesso.',id:r.lastID});}catch(err){if(String(err.message).includes('UNIQUE'))return res.status(409).json({erro:'Já existe uma conta com este e-mail.'});console.error(err);return res.status(500).json({erro:'Erro ao criar usuário.'});}}
async function atualizarUsuario(req,res){const id=Number(req.params.id),atual=await get('SELECT * FROM usuarios WHERE id=?',[id]);if(!atual)return res.status(404).json({erro:'Usuário não encontrado.'});const b=req.body||{},role=b.role??atual.role,ativo=b.ativo===undefined?atual.ativo:(b.ativo?1:0);if(!['admin','usuario'].includes(role))return res.status(400).json({erro:'Perfil de usuário inválido.'});if(id===req.usuario.id&&(!ativo||role!=='admin'))return res.status(400).json({erro:'Você não pode desativar ou remover seu próprio perfil de administrador.'});if(atual.role==='admin'&&(role!=='admin'||!ativo)){const admins=await get("SELECT COUNT(*) AS n FROM usuarios WHERE role='admin' AND ativo=1");if((admins?.n||0)<=1)return res.status(400).json({erro:'O sistema precisa manter pelo menos um administrador ativo.'});}const nome=String(b.nome??atual.nome).trim(),email=normalizarEmail(b.email??atual.email),masp=String(b.masp??atual.masp).trim();if(!nome||!email||!masp)return res.status(400).json({erro:'Nome, e-mail e MASP são obrigatórios.'});try{const unidade=await resolverUnidade({unidadeId:b.unidadeId??b.unidade_id??atual.unidade_id,unidade:b.unidade??atual.unidade},true);if(!unidade)return res.status(400).json({erro:'Selecione uma unidade ativa cadastrada no Nexus.'});await run(`UPDATE usuarios SET nome=?,email=?,masp=?,unidade=?,unidade_id=?,role=?,ativo=?,atualizado_em=CURRENT_TIMESTAMP WHERE id=?`,[nome,email,masp,unidade.nome,unidade.id,role,ativo,id]);if(!ativo)await run('DELETE FROM auth_sessions WHERE usuario_id=?',[id]);return res.json({mensagem:'Usuário atualizado com sucesso.'});}catch(err){if(String(err.message).includes('UNIQUE'))return res.status(409).json({erro:'Já existe uma conta com este e-mail.'});console.error(err);return res.status(500).json({erro:'Erro ao atualizar usuário.'});}}
async function redefinirSenha(req,res){const id=Number(req.params.id),senha=String(req.body?.senha||'');if(senha.length<8)return res.status(400).json({erro:'A nova senha deve possuir pelo menos 8 caracteres.'});const u=await get('SELECT id FROM usuarios WHERE id=?',[id]);if(!u)return res.status(404).json({erro:'Usuário não encontrado.'});const hash=await bcrypt.hash(senha,10);await run('UPDATE usuarios SET senha=?,atualizado_em=CURRENT_TIMESTAMP WHERE id=?',[hash,id]);if(id!==req.usuario.id)await run('DELETE FROM auth_sessions WHERE usuario_id=?',[id]);return res.json({mensagem:'Senha redefinida com sucesso.'});}
module.exports={listarUnidadesPublicas,bootstrapStatus,registrar,login,sessaoAtual,logout,listarUsuarios,criarUsuario,atualizarUsuario,redefinirSenha};
